Change case to Cordova
Having the lowercase "CORDOVA" causes a build error when using this plugin:

platforms/ios/CarnetJove/Plugins/uk.co.workingedge.phonegap.plugin.LaunchNavigator/LaunchNavigator.h:32:9: fatal error: 'CORDOVA/CDVPlugin.h' file not found
#import "CORDOVA/CDVPlugin.h"
        ^
1 error generated.

This commit fixes it